# Install Declarative Onboarding RPM
  # Push Declarative Onboarding declaration to BIG-IP
  - name: Push DO declaration to BIG-IP
    uri:
      url: "{{ BIGIP }}/mgmt/shared/appsvcs/declare"
      method: POST
      user: "admin"
      password: "{{ BIGIP_PASSWORD }}"
      body: "{{ lookup('file', 'files/as3_nginx.json') }}"
      status_code: 202
      timeout: 300
      body_format: json
      validate_certs: no