---
- hosts: localhost
  become: true
  gather_facts: False
  tasks:
  # Push AS3 declaration to BIG-IP
  - name: Push AS3 declaration to BIG-IP
    uri:
      url: "https://{{ BIGIP }}:8443/mgmt/shared/appsvcs/declare"
      method: POST
      user: "admin"
      password: "{{ BIGIP_PASSWORD }}"
      body: "{{ lookup('file', 'as3_nginx.json') }}"
      status_code: 202
      timeout: 300
      body_format: json
      validate_certs: no