---
- hosts: localhost
  gather_facts: False
  tasks:
  # Change the BIG-IP admin password
  - name: Change BIG-IP admin password
    bigip_command:
      provider:
        server: "{{ BIGIP }}"
        ssh_keyfile: "{{ SSH_KEYFILE }}"
        transport: cli
        user: "admin"
      commands: 
        - modify auth user admin password {{ BIGIP_PASSWORD }}
        - save sys config
  # Install AS3 
  - name: Download foo.conf
    get_url:
      url: https://github.com/F5Networks/f5-appsvcs-extension/raw/master/dist/lts/f5-appsvcs-3.5.1-5.noarch.rpm
      dest: ./as3.rpm
  - name: Install AS3
    bigip_iapplx_package:
      package: "./as3.rpm"
      provider:
        server: "{{ BIGIP }}"
        server_port: "8443"
        transport: rest
        user: "admin"
        password: "{{ BIGIP_PASSWORD }}"
        validate_certs: no
  # Push AS3 declaration to BIG-IP
  - name: Push AS3 declaration to BIG-IP
    uri:
      url: "https://{{ BIGIP }}:8443/mgmt/shared/appsvcs/declare"
      method: POST
      user: "admin"
      password: "{{ BIGIP_PASSWORD }}"
      body: "{{ lookup('file', 'as3_nginx.json') }}"
      status_code: 200
      timeout: 300
      body_format: json
      validate_certs: no