---
- hosts: http
  become: true
  gather_facts: False
  pre_tasks:
  - name: Install python2 for Ansible
    raw: bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qqy python-minimal)"
    register: output
    changed_when: output.stdout != ""
  - name: Gathering Facts
    setup:
  roles:
    - role: nginxinc.nginx
  post_tasks:
    - name: checkout repo
      git:
        repo: "{{ GIT_REPO_URL }}"
        dest: /srv/checkout
      register: git_output
    - name: copy website
      copy:
        src: /srv/checkout/html/index.html
        remote_src: yes
        dest: /usr/share/nginx/html/index.html
    - name: copy configs
      copy:
        src: /srv/checkout/conf.d/default.conf
        remote_src: yes
        dest: /etc/nginx/conf.d/default.conf
    - name: restart NGINX
      service:
        name: nginx
        state: restarted